version: '3.8'

services:
  neo4j5:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/testpassword
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    volumes:
      - /mnt/data/neo4j5/data:/data
      - /mnt/data/neo4j5/logs:/logs
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
