version: '3.8'

services:
  glusterfs:
    image: gluster/gluster-centos:latest
    container_name: glusterfs
    privileged: true
    network_mode: host
    environment:
      - GLUSTERFS_NODE=localhost
    volumes:
      - /mnt/data/glusterfs:/data
      - /etc/glusterfs:/etc/glusterfs
      - /var/lib/glusterd:/var/lib/glusterd
      - /var/log/glusterfs:/var/log/glusterfs
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
