version: '3.8'

services:
  nats:
    image: nats:2
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - /mnt/data/nats:/data
    command: ["-js", "-sd", "/data"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
